### ISSUE TITLE
Issues / Todo

### ISSUE THREAD

**Issue by jmamma** [jmamma/MIDICtrl20_MegaCommand#157]
**Reported issues:**

- [ ] LFO track SPD parameter is working but not saved when assigned on PAN Ram 1 & 2.
- [ ] Also I cannot save the volume of the ram machine, each time i launch (slice/dice) the Ram machine is @ full level by default. It’s complicate to use it this way without having a big difference of level with other tracks.
- [ ] Possible lockup on slide page, GUI unresponsive.

- [ ] Chromatic/Step  Seq:
> EFM-HH or EFM-CB in ‘tonal’ (these are two I could recreate the issue with, havent tried with other)
    In Chromatic if I enter a note below F1 (PTCH 8) while rec, the note gets perfectly recorded
    If I now change to step edit in order to make some adjustments whatsover and press a just recorded step with a PTCH below 8 it automatically switches its PTCH to 8
> If the machine is in ‘default’ the results are somewhat identical as notes that have been entered with a PTCH beneath the lowest known to step edit just slip back to it’s lowest known value once pressed
Also I think there is an offset in octaves when using midi keys in the Chromatic and Step edit page.
    If ‘tonal’ is activated and Midi Keys are in omni, on Chromatic, OCT is 0, D1 is playing PTCH 2
    If I change now to step edit D1 is playing PTCH 74
    The results are similar if the machine is in ‘default’, whereas ‘tonal’ has an offset of 3 Octaves (Holy cow, thanks for the additional octaves <3), ‘default’ has an offset of 1 Octave

**Features:** 
- [ ] forward MIDI data from PORT2 -> PORT1 or PORT1-> PORT2.  simultaneously. 
- [ ] Program change
